### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [saroar/quote#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by saroar** [comment]
thanks for ur advice i was not test on my mobile but after get ur email i check it yaa it does look good but i follow all anyway let check it and make better ui for mobile device :)

**Comment by saroar** [comment]
can u give me some like please where i can checkout about mobile meta tag but when i make my browser its work but in my mobile it does not work don't know why :( but still trying

**Comment by kenmazaika** [comment]
I suggest you google around a little more and try to find the solution on your own.  It's a valuable skill.

If you still can't find the solution, check out this video I made a while ago here:
https://vimeo.com/75718091

**Comment by saroar** [comment]
http://prntscr.com/8gbjay here u can see

**Comment by saroar** [comment]
ok done its awesome man now :)let me push it in heroku :)

**Comment by kenmazaika** [comment]
thumbs up! :)
